# fly.toml file generated for flump-f955 on 2023-06-04T17:26:05+01:00

app = "flump-f955"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lhr"

[deploy]
  release_command = "bash ./scripts/migrate.sh"

[env]
  METRICS_PORT = "8081"
  PORT = "8080"

[metrics]
  port = 8081
  path = "/metrics"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 3

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    protocol = "http"
