name: release-please
on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: write
  pull-requests: write
  id-token: write
  pages: write

jobs:
  release:
    name: 📦 Release
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.release.outputs.paths_released }}
      releases_created: ${{ steps.release.outputs.releases_created }}
    steps:
      - id: release
        uses: googleapis/release-please-action@v4

      - name: "[Debug] release-please outputs"
        env:
          RELEASE_PLEASE_CONTEXT: ${{ toJson(steps.release.outputs) }}
        run: echo "$RELEASE_PLEASE_CONTEXT"

  deploy-separate:
    name: 🚀 Deploy
    needs: release
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.releases_created == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        path: ${{fromJson(needs.release.outputs.paths_released)}}

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 👀 Read app name
        uses: SebRollen/toml-action@v1.2.0
        id: app_name
        with:
          file: ${{ matrix.path }}/fly.toml
          field: app

      - name: 🚀 Deploy ${{ steps.app_name.outputs.value }}
        uses: superfly/flyctl-actions/setup-flyctl@master

      - run: "cd ${{ matrix.path }} && pnpm panda init && flyctl deploy --remote-only --build-arg COMMIT_SHA=${{ github.sha }} --app ${{ steps.app_name.outputs.value }}${{github.ref == 'refs/heads/dev' && '-staging' || ''}} "
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
